name: Gradle Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-release:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
      
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
      
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper

    - name: Change Wrapper permissions
      run: chmod +x ./gradlew

    - name: Run build with Gradle Wrapper
      run: ./gradlew build --no-daemon

    - name: Create New Release
      uses: softprops/action-gh-release@v1
      with:
        files: '**/Sudoku.jar'
        fail_on_unmatched_files: true
        generate_release_notes: true

#    - name: Create new release
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: >-
#        gh release create ${{ github.ref_name }}
#        "Sudoku.jar#Executable JAR"
#        --generate-notes
#        --title "Version ${{ github.ref_name }} (or some other name)"


      
